// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_appsync_graphqlEndpoint": "https://v4ngpupzgffdpdejyxb3ruffea.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-bzalp6ck2bhepfss5sahtq62rq",
    "aws_content_delivery_bucket": "react-aws-serveless-20200515013106-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "eu-west-2",
    "aws_content_delivery_url": "https://d38npktnnhv0q4.cloudfront.net"
};


export default awsmobile;
